### ISSUE TITLE
Wykonanie

### ISSUE THREAD

**Issue by Gawinooo** [ProjektZespolowyDGOGPGPA/Styl-firmowy-projektu#1]
@GallAn0nim Do opracowania jest: 
o Logo (logotyp, symbol), tagline (slogan), wizytówkę;
o Papier firmowy;
o Szablon firmowy do opracowania dokumentacji projektowej.
Ostateczny termin oddania:15.03.2016 23:59

**Comment by GallAn0nim** [comment]
Projekty loga oraz wizytówki zostały uplodowane proszę o krytykę i komentarz
